[project]
name = "hn_bot"
version = "0.1.0"
description = "A telegram bot to scrape hacker news, but in a less distracting way than the bots that currently exist."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["httpx>=0.28.1"]
