[project]
name = "hn-bot"
version = "0.0.1"
description = "A telegram bot to scrape hacker news, but in a less distracting way than the bots that currently exist."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "python-telegram-bot[job-queue]>=21.10",
]
